name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean binaries
      run: make clean
    - name: Build DeSiGNAR
      run: make library
    - name: Build Samples
      run: make samples
    - name: Build Tests
      run: make tests
    - name: Running Tests
      run: sh run_tests.sh