name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean binaries
      run: make clean
    - name: Build Designar
      run: make library
    - name: Build Samples
      run: make samples
    - name: Build Tests
      run: make tests
